/**
 * Canonical API error codes.
 *
 * Naming convention: <DOMAIN>_<NOUN>_<STATE>
 * See: agents/backend-agent/API_CONVENTIONS.md §12
 *
 * Adding a new code:
 *   1. Add it to this enum
 *   2. Add a matching i18n entry in apps/api/src/i18n/errors/<locale>.json
 *   3. Document it in docs/api/errors.md (auto-generated from this file in the future)
 */

export const ErrorCode = {
  // ── Generic ──
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // ── Auth ──
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  // ── User ──
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',

  // ── Designer ──
  DESIGNER_KYC_INCOMPLETE: 'DESIGNER_KYC_INCOMPLETE',
  DESIGNER_KYC_REJECTED: 'DESIGNER_KYC_REJECTED',
  DESIGNER_PAYOUT_NOT_CONFIGURED: 'DESIGNER_PAYOUT_NOT_CONFIGURED',
  DESIGNER_TIER_INSUFFICIENT: 'DESIGNER_TIER_INSUFFICIENT',

  // ── Watch face ──
  WATCHFACE_NOT_FOUND: 'WATCHFACE_NOT_FOUND',
  WATCHFACE_IR_INVALID: 'WATCHFACE_IR_INVALID',
  WATCHFACE_IP_REVIEW_PENDING: 'WATCHFACE_IP_REVIEW_PENDING',
  WATCHFACE_IP_REVIEW_REJECTED: 'WATCHFACE_IP_REVIEW_REJECTED',
  WATCHFACE_NOT_PUBLISHED: 'WATCHFACE_NOT_PUBLISHED',

  // ── Build ──
  BUILD_DEVICE_UNSUPPORTED: 'BUILD_DEVICE_UNSUPPORTED',
  BUILD_MEMORY_BUDGET_EXCEEDED: 'BUILD_MEMORY_BUDGET_EXCEEDED',
  BUILD_COMPILE_FAILED: 'BUILD_COMPILE_FAILED',

  // ── Purchase ──
  PURCHASE_PAYMENT_FAILED: 'PURCHASE_PAYMENT_FAILED',
  PURCHASE_ALREADY_OWNED: 'PURCHASE_ALREADY_OWNED',
  PURCHASE_REFUND_DENIED: 'PURCHASE_REFUND_DENIED',

  // ── Subscription ──
  SUBSCRIPTION_NOT_ACTIVE: 'SUBSCRIPTION_NOT_ACTIVE',
  SUBSCRIPTION_QUOTA_EXCEEDED: 'SUBSCRIPTION_QUOTA_EXCEEDED',

  // ── AI generation ──
  AI_BUDGET_EXCEEDED_USER: 'AI_BUDGET_EXCEEDED_USER',
  AI_BUDGET_EXCEEDED_PLATFORM: 'AI_BUDGET_EXCEEDED_PLATFORM',
  AI_PROMPT_BLOCKED: 'AI_PROMPT_BLOCKED',
  AI_OUTPUT_BLOCKED: 'AI_OUTPUT_BLOCKED',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',

  // ── Webhooks ──
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_DUPLICATE_EVENT: 'WEBHOOK_DUPLICATE_EVENT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    details?: Record<string, unknown>;
    requestId: string;
  };
}
